"""empty message

Revision ID: 843854a9b135
Revises: c4407a3bc344
Create Date: 2024-06-27 10:03:14.267526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '843854a9b135'
down_revision = 'c4407a3bc344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
